import {
  ApplicationGraph,
  binary,
  describeAuthoringKind,
  field,
  fieldId,
  literal,
  nodeId,
  primitiveType,
  ref,
  stateLocation,
} from '@cynodia/axiom-core';
import type {
  ActionDef,
  AuthorizationPolicyDef,
  EntityDef,
  QueryDef,
  ReadPolicyDef,
  StateDef,
} from '@cynodia/axiom-core';
import { AgentAPI } from './api.js';

/**
 * `axiom.conformance.v10` — the tooling/explainability conformance tier (spec16 §123-126).
 *
 * Server IR conformance (`axiom.conformance.v1`-`v9`, `packages/server/conformance/`) checks
 * that a portable *execution* document produces a required result on a real backend
 * (memory/SQLite). AgentAPI carries no execution semantics of its own — it is static
 * analysis over a graph — so this tier checks the **tooling contract** instead: given a
 * graph, does each canonical inspection/analysis/authoring/editing entry point produce the
 * result independently specified below (spec16 §121, §125 — expectations are hand-written,
 * never generated by calling the implementation under test).
 *
 * Each fixture is self-contained (builds its own tiny graph) so a fixture can be read and
 * verified without cross-referencing another.
 */
export const TOOLING_CONFORMANCE_CONTRACT = 'axiom.conformance.v10';

export type ToolingConformanceCategory =
  | 'inventory'
  | 'dependencies'
  | 'explain-action'
  | 'explain-query'
  | 'explain-workflow'
  | 'authorization-analysis'
  | 'capabilities'
  | 'semantic-diff'
  | 'diagnostics'
  | 'authoring-schema'
  | 'graph-edit'
  | 'native-boundary';

export interface ToolingConformanceFixture {
  id: string;
  category: ToolingConformanceCategory;
  description: string;
  run: () => unknown;
  expected: unknown;
}

export interface ToolingConformanceResult {
  id: string;
  category: ToolingConformanceCategory;
  passed: boolean;
  actual?: unknown;
  expected?: unknown;
  error?: string;
}

function deepEqual(a: unknown, b: unknown): boolean {
  return JSON.stringify(sortKeysDeep(a)) === JSON.stringify(sortKeysDeep(b));
}

function sortKeysDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
        .map(([k, v]) => [k, sortKeysDeep(v)]),
    );
  }
  return value;
}

// ------------------------------------------------------------------------------- fixtures

const E_USER = nodeId('ct_entity_user');
const F_UID = fieldId('ct_field_uid');
const F_ROLE = fieldId('ct_field_role');
const S_COUNT = nodeId('ct_state_count');
const A_BUMP = nodeId('ct_action_bump');
const A_NATIVE = nodeId('ct_action_native');
const Q_USERS = nodeId('ct_query_users');
const P_ADMIN = nodeId('ct_policy_admin');
const ROW = nodeId('ct_row');

function fixtureGraph(): ApplicationGraph {
  const g = new ApplicationGraph('ct-graph', 'Conformance Fixture');
  g.addNode<EntityDef>({
    id: E_USER,
    kind: 'entity',
    identityFieldId: F_UID,
    fields: [
      { id: F_UID, valueType: primitiveType('string'), required: true },
      { id: F_ROLE, valueType: primitiveType('string'), required: true },
    ],
  });
  g.setPrincipalEntity(E_USER);
  g.addNode<StateDef>({ id: S_COUNT, kind: 'state', authority: 'server', valueType: primitiveType('number'), initialValue: 0 });
  g.addNode<AuthorizationPolicyDef>({
    id: P_ADMIN,
    kind: 'authorization-policy',
    allow: binary('eq', field(ref(nodeId('axiom_principal')), F_ROLE), literal('admin')),
  });
  g.addNode<ActionDef>({
    id: A_BUMP,
    kind: 'action',
    authorizationPolicy: P_ADMIN,
    operations: [{ kind: 'set', target: stateLocation(S_COUNT), value: binary('add', ref(S_COUNT), literal(1)) }],
  });
  g.addNode<ActionDef>({ id: A_NATIVE, kind: 'action', operations: [{ kind: 'native', implementationId: 'legacy.op' }] });
  g.addNode<QueryDef>({
    id: Q_USERS,
    kind: 'query',
    source: E_USER,
    rowScopeId: ROW,
    authorizationPolicy: P_ADMIN,
    pagination: { strategy: 'offset', maxPageSize: 50 },
  } as QueryDef);
  return g;
}

/**
 * A self-contained entity + query + (optionally referenced) read policies, for the F3
 * attach/detach/replace fixtures. `declarePolicies` names every `ReadPolicyDef` node to
 * declare (both, for a "replace" scenario), independent of which one `readPolicyId` points
 * at, so the diff reflects only the reference change, not a policy node appearing/vanishing.
 */
function readPolicyFixtureGraph(readPolicyId: string | undefined, ...declarePolicies: string[]): ApplicationGraph {
  const g = new ApplicationGraph('ct-read-policy-graph', 'Read Policy Fixture');
  const entityId = nodeId('read_policy_entity');
  const identityField = fieldId('read_policy_entity_id');
  g.addNode<EntityDef>({
    id: entityId,
    kind: 'entity',
    identityFieldId: identityField,
    fields: [{ id: identityField, valueType: primitiveType('string'), required: true }],
  });
  for (const policyId of new Set([...(readPolicyId ? [readPolicyId] : []), ...declarePolicies])) {
    g.addNode<ReadPolicyDef>({
      id: nodeId(policyId),
      kind: 'read-policy',
      entityId,
      rowScopeId: nodeId('read_policy_row'),
      predicate: literal(true),
    });
  }
  g.addNode<QueryDef>({
    id: nodeId('read_policy_query'),
    kind: 'query',
    source: entityId,
    rowScopeId: nodeId('read_policy_query_row'),
    pagination: { strategy: 'offset', maxPageSize: 50 },
    ...(readPolicyId ? { readPolicyId: nodeId(readPolicyId) } : {}),
  } as QueryDef);
  return g;
}

export function toolingConformanceFixtures(): ToolingConformanceFixture[] {
  return [
    {
      id: 'inventory-counts-by-kind',
      category: 'inventory',
      description: 'the inventory reports the exact node count for every declared kind',
      run: () => new AgentAPI(fixtureGraph()).inventory().countsByKind.action,
      expected: 2,
    },
    {
      id: 'dependencies-transitive-action-to-policy',
      category: 'dependencies',
      description: 'a policy-guarded action transitively depends on its policy',
      run: () => new AgentAPI(fixtureGraph()).getTransitiveDependencies(A_BUMP).ids.includes(String(P_ADMIN)),
      expected: true,
    },
    {
      id: 'dependencies-provenance-is-structural',
      category: 'dependencies',
      description: 'explainDependency names the references edge between action and policy',
      run: () => {
        const provenance = new AgentAPI(fixtureGraph()).explainDependency(A_BUMP, P_ADMIN);
        return provenance?.edges.map((e) => e.kind);
      },
      expected: ['references'],
    },
    {
      id: 'explain-action-reads-writes-and-authorization',
      category: 'explain-action',
      description: 'explainAction reports the write set and policy protection of a guarded action',
      run: () => {
        const explanation = new AgentAPI(fixtureGraph()).explainAction(A_BUMP)!;
        return { writes: explanation.writes.stateIds, authorization: explanation.authorization.kind };
      },
      expected: { writes: [String(S_COUNT)], authorization: 'policy' },
    },
    {
      id: 'explain-query-authorization-and-liveness',
      category: 'explain-query',
      description: 'explainQuery composes the policy protection onto the base query explanation',
      run: () => {
        const explanation = new AgentAPI(fixtureGraph()).explainQuery(Q_USERS)!;
        return { source: explanation.source, authorization: explanation.authorization.kind };
      },
      expected: { source: String(E_USER), authorization: 'policy' },
    },
    {
      id: 'authorization-analysis-unprotected-surfaces',
      category: 'authorization-analysis',
      description: 'the native-operation action has no authorization boundary and is reported unprotected',
      run: () =>
        new AgentAPI(fixtureGraph())
          .analyzeAuthorization()
          .unprotected.some((u) => u.nodeId === String(A_NATIVE)),
      expected: true,
    },
    {
      id: 'authorization-decision-absent-role-denies',
      category: 'authorization-analysis',
      description: 'a principal with no role field cannot satisfy an admin-role policy (fail closed)',
      run: () => new AgentAPI(fixtureGraph()).explainAuthorizationDecision({ actionId: A_BUMP, principal: {} })?.decision,
      expected: 'DENY',
    },
    {
      id: 'capabilities-server-state-requires-persistence',
      category: 'capabilities',
      description: 'a server-authoritative StateDef requires the persistence capability',
      run: () => new AgentAPI(fixtureGraph()).analyzeCapabilities().requiredCapabilities.includes('persistence'),
      expected: true,
    },
    {
      id: 'semantic-diff-authorization-change-is-tagged',
      category: 'semantic-diff',
      description: 'detaching a policy from an action is classified as an authorization change, additive with its own kind category (spec16pt2 §40)',
      run: () => {
        const before = fixtureGraph();
        const after = fixtureGraph();
        const action = after.getNode<ActionDef>(A_BUMP)!;
        delete (action as { authorizationPolicy?: unknown }).authorizationPolicy;
        after.updateNode(action);
        const diff = new AgentAPI(after).semanticDiff(before);
        return diff.entries.find((e) => e.nodeId === String(A_BUMP))?.categories;
      },
      expected: ['semantic', 'authorization'],
    },
    {
      id: 'semantic-diff-read-policy-attach-is-authorization',
      category: 'semantic-diff',
      description: 'spec16pt2 F3/§34-35: attaching a QueryDef.readPolicyId is classified query + authorization',
      run: () => {
        const before = readPolicyFixtureGraph(undefined);
        const after = readPolicyFixtureGraph('read_policy_owner');
        const diff = new AgentAPI(after).semanticDiff(before);
        return diff.entries.find((e) => e.nodeId === 'read_policy_query')?.categories;
      },
      expected: ['query', 'authorization'],
    },
    {
      id: 'semantic-diff-read-policy-detach-is-authorization',
      category: 'semantic-diff',
      description: 'spec16pt2 F3 exact reproduction: detaching a QueryDef.readPolicyId is classified query + authorization',
      run: () => {
        const before = readPolicyFixtureGraph('read_policy_owner');
        const after = readPolicyFixtureGraph(undefined);
        const diff = new AgentAPI(after).semanticDiff(before);
        return diff.entries.find((e) => e.nodeId === 'read_policy_query')?.categories;
      },
      expected: ['query', 'authorization'],
    },
    {
      id: 'semantic-diff-read-policy-replace-is-authorization',
      category: 'semantic-diff',
      description: 'spec16pt2 §36: replacing one read policy reference for another is classified authorization',
      run: () => {
        const before = readPolicyFixtureGraph('read_policy_owner', 'read_policy_other');
        const after = readPolicyFixtureGraph('read_policy_other', 'read_policy_other');
        const diff = new AgentAPI(after).semanticDiff(before);
        return diff.entries.find((e) => e.nodeId === 'read_policy_query')?.categories.includes('authorization');
      },
      expected: true,
    },
    {
      id: 'diagnostics-unresolved-reference-is-structured',
      category: 'diagnostics',
      description: 'removing a state a policy-guarded action writes yields a structured, non-empty diagnostic set',
      run: () => {
        const result = new AgentAPI(fixtureGraph()).proposeEdit({
          changes: [{ kind: 'remove-node', nodeId: S_COUNT, node: {} as StateDef }],
        });
        return { applied: result.applied, hasErrors: (result.validation?.errors.length ?? 0) > 0 };
      },
      expected: { applied: false, hasErrors: true },
    },
    {
      id: 'authoring-schema-covers-authorization-policy',
      category: 'authoring-schema',
      description: 'the authoring schema describes AuthorizationPolicyDef with a required allow field',
      run: () => {
        const descriptor = describeAuthoringKind('authorization-policy');
        return descriptor?.fields.some((f) => f.name === 'allow' && f.required);
      },
      expected: true,
    },
    {
      id: 'graph-edit-valid-add-is-accepted',
      category: 'graph-edit',
      description: 'a self-contained added action validates and appears in the diff as added',
      run: () => {
        const id = nodeId('ct_action_new');
        const result = new AgentAPI(fixtureGraph()).proposeEdit({
          changes: [{ kind: 'add-node', nodeId: id, node: { id, kind: 'action', operations: [] } as ActionDef }],
        });
        return { applied: result.applied, added: result.diff?.entries.some((e) => e.nodeId === String(id) && e.changeKind === 'added') };
      },
      expected: { applied: true, added: true },
    },
    {
      id: 'native-boundary-is-explicit-and-opaque',
      category: 'native-boundary',
      description: 'a NativeOperation with no declared effects is reported as opaque, never hidden',
      run: () => {
        const summary = new AgentAPI(fixtureGraph()).summarizeNativeOperations();
        return { count: summary.count, opaqueCount: summary.opaqueCount };
      },
      expected: { count: 1, opaqueCount: 1 },
    },
  ];
}

export function runToolingConformanceFixture(fixture: ToolingConformanceFixture): ToolingConformanceResult {
  try {
    const actual = fixture.run();
    return { id: fixture.id, category: fixture.category, passed: deepEqual(actual, fixture.expected), actual, expected: fixture.expected };
  } catch (error) {
    return { id: fixture.id, category: fixture.category, passed: false, error: error instanceof Error ? error.message : String(error) };
  }
}

export function runToolingConformanceSuite(): ToolingConformanceResult[] {
  return toolingConformanceFixtures().map(runToolingConformanceFixture);
}
