/**
 * Everything this package uses from the rest of Axiom, re-exported through one module.
 *
 * Keeping the imports in one place makes the dependency surface of the authoritative
 * runtime explicit: it is the semantic engine and nothing else. No transport, no database
 * driver and no host API appears here.
 */
export type {
  ActionDef,
  AnyNode,
  ApplicationIR,
  Authority,
  AuthorityCompatibilityKey,
  CompatibilityComparison,
  ConstraintDef,
  EntityDef,
  EventDef,
  Expression,
  FieldDef,
  FieldId,
  IntegrationDef,
  IntegrationOperationDef,
  LiteralValue,
  MigrationDef,
  MigrationOperation,
  MigrationOperationKind,
  NodeId,
  Operation,
  SchemaChangeClass,
  SchemaDiff,
  SchemaDiffEntry,
  SchemaProjection,
  QueryAggregate,
  QueryAggregateFunction,
  QueryDef,
  LiveCapability,
  LiveChange,
  LiveQueryDelta,
  MaterializedResult,
  QueryDependencySet,
  CommitChangeset,
  QueryNullsOrder,
  QueryPagination,
  QueryParameter,
  QueryProjection,
  QueryRelationshipUse,
  QuerySortDirection,
  QuerySortKey,
  ReadPolicyDef,
  RelationshipDef,
  RelationshipCardinality,
  ServerIR,
  StateDef,
  StorageDef,
  SubscriptionDef,
  SubscriptionBackpressurePolicy,
  SubscriptionLifecycleState,
  TransitionConstraintDef,
  TriggerDef,
  TriggerSpec,
  TypeRef,
} from '@cynodia/axiom-core';

export type {
  ActionOutcome,
  ActionResult,
  EffectIntentRecord,
  RuntimeDiagnostic,
  RuntimeDiagnosticCode,
} from '@cynodia/axiom-runtime';

export { PRINCIPAL, RUNTIME_DIAGNOSTIC_CODES, SERVER_IR_CONTRACT } from './runtime-deps.js';
export {
  MIGRATION_OLD_SCOPE,
  MIGRATION_OPERATION_KINDS,
  diffSchema,
  canonicalJSON,
  walkExpression,
  applyDelta,
  commitAffectsQuery,
  diffResults,
  queryDependencies,
  queryLiveCapability,
  rowKey,
  LIVE_QUERY_NONDETERMINISTIC_BUILTINS,
  fingerprintProjection,
  migrationCoversDiff,
  migrationExpressions,
  migrationOperationEntityId,
  migrationOperationExpressions,
  migrationOperationFieldIds,
  migrationOperationReadFieldIds,
  migrationPath,
  schemaFingerprint,
  schemaProjection,
  semanticFingerprint,
  semanticProjection,
  authorityCompatibilityKey,
  compatibilityKeyString,
  compareAuthorityCompatibility,
  SEMANTIC_FINGERPRINT_VERSION,
  sortMigrations,
} from '@cynodia/axiom-core';
export {
  BLOB_CHECKSUM_FIELD,
  BLOB_FILENAME_FIELD,
  BLOB_KEY_FIELD,
  BLOB_MEDIA_TYPE_FIELD,
  BLOB_SIZE_FIELD,
  DEFAULT_QUERY_MAX_PAGE_SIZE,
  DEFAULT_QUERY_PAGE_SIZE,
  DEFAULT_RELATIONSHIP_PAGE_SIZE,
  queryDefaultPageSize,
  queryExpressions,
  queryIsAggregate,
  queryIsGrouped,
  queryMaxPageSize,
  queryPaginationStrategy,
  queryRowEntityId,
  relationshipIsToOne,
  relationshipTargetEntityId,
  sortKeyDirection,
  sortKeyNulls,
  subscriptionAutoStart,
  subscriptionBackpressure,
  subscriptionDeduplicationWindow,
  subscriptionFailurePolicy,
  subscriptionIsRequired,
  subscriptionMaxAttempts,
  subscriptionQueueLimit,
  subscriptionReconnectPolicy,
  subscriptionSourceName,
} from '@cynodia/axiom-core';
